pyecharts/final design/test01/test01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('clinicaltrial/', include('clinicaltrial.urls'))
]

pyecharts/final design/test01/clinicaltrial/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Clinicaltrial(models.Model):
    rank = models.IntegerField(db_column='Rank', blank=True, null=True)  # Field name made lowercase.
    trial_id = models.CharField(db_column='Trial ID', primary_key=True, max_length=45)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    title = models.CharField(db_column='Title', max_length=500, blank=True, null=True)  # Field name made lowercase.
    brief_title = models.CharField(db_column='Brief title', max_length=500, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    acronym = models.CharField(db_column='Acronym', max_length=500, blank=True, null=True)  # Field name made lowercase.
    abstract = models.CharField(db_column='Abstract', max_length=1000, blank=True, null=True)  # Field name made lowercase.
    detailed_description = models.CharField(db_column='Detailed Description', max_length=1500, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    start_year = models.IntegerField(db_column='Start_Year', blank=True, null=True)  # Field name made lowercase.
    completion_year = models.IntegerField(db_column='Completion_Year', blank=True, null=True)  # Field name made lowercase.
    phase = models.CharField(db_column='Phase', max_length=45, blank=True, null=True)  # Field name made lowercase.
    conditions = models.CharField(db_column='Conditions', max_length=500, blank=True, null=True)  # Field name made lowercase.
    intervention = models.CharField(db_column='Intervention', max_length=500, blank=True, null=True)  # Field name made lowercase.
    gender = models.CharField(db_column='Gender', max_length=30, blank=True, null=True)  # Field name made lowercase.
    registry = models.CharField(db_column='Registry', max_length=30, blank=True, null=True)  # Field name made lowercase.
    investigators_contacts = models.CharField(db_column='Investigators/Contacts', max_length=500, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    sponsors_collaborators = models.CharField(db_column='Sponsors/Collaborators', max_length=500, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    grid_ids = models.CharField(db_column='GRID IDs', max_length=100, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    city_of_sponsor_collaborator = models.CharField(db_column='City of Sponsor/Collaborator', max_length=80, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    state_of_sponsor_collaborator = models.CharField(db_column='State of Sponsor/Collaborator', max_length=45, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    country_of_sponsor_collaborator = models.CharField(db_column='Country of Sponsor/Collaborator', max_length=100, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    collaborating_funders = models.CharField(db_column='Collaborating Funders', max_length=100, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    funder_group = models.CharField(db_column='Funder Group', max_length=100, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    funder_country = models.CharField(db_column='Funder Country', max_length=100, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    source_linkout = models.CharField(db_column='Source Linkout', max_length=100, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    dimensions_url = models.CharField(db_column='Dimensions URL', max_length=100, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    for_anzsrc_categories = models.CharField(db_column='FOR (ANZSRC) Categories', max_length=500, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    rcdc_categories = models.CharField(db_column='RCDC Categories', max_length=500, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    hrcs_hc_categories = models.CharField(db_column='HRCS HC Categories', max_length=500, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    hrcs_rac_categories = models.CharField(db_column='HRCS RAC Categories', max_length=500, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    icrp_cancer_types = models.CharField(db_column='ICRP Cancer Types', max_length=500, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    icrp_cso_categories = models.CharField(db_column='ICRP CSO Categories', max_length=500, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    city1 = models.CharField(db_column='City1', max_length=45, blank=True, null=True)  # Field name made lowercase.
    city2 = models.CharField(db_column='City2', max_length=45, blank=True, null=True)  # Field name made lowercase.
    state1 = models.CharField(db_column='State1', max_length=45, blank=True, null=True)  # Field name made lowercase.
    state2 = models.CharField(db_column='State2', max_length=45, blank=True, null=True)  # Field name made lowercase.
    country1 = models.CharField(db_column='Country1', max_length=45, blank=True, null=True)  # Field name made lowercase.
    country2 = models.CharField(db_column='Country2', max_length=45, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'clinicaltrial'


class ForAnzsrcData(models.Model):
    no = models.CharField(db_column='No', primary_key=True, max_length=500)  # Field name made lowercase.
    quantity = models.IntegerField(db_column='Quantity', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'for_anzsrc_data'


class State(models.Model):
    state = models.CharField(primary_key=True, max_length=50)
    state_count = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'state'


class User(models.Model):
    username = models.CharField(primary_key=True, max_length=45)
    password = models.CharField(max_length=45)
    email = models.CharField(max_length=45, blank=True, null=True)
    phone = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'user'

pyecharts/final design/test01/templates/add_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加成功</title>
</head>
<body>
<h1>添加成功</h1>
<a href="/clinicaltrial/show">转跳回到首页</a>


</body>
</html>

pyecharts/final design/test01/templates/edit_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改成功</title>
</head>
<body>
<h1>修改成功</h1>
<a href="/clinicaltrial/show">转跳回到首页</a>


</body>
</html>

pyecharts/final design/test01/templates/guest.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>我国临床试验研究情况</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- jQuery UI -->
    <link href="https://code.jquery.com/ui/1.10.3/themes/redmond/jquery-ui.css" rel="stylesheet" media="screen">
    <!-- Bootstrap -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="/static/css/style.css" rel="stylesheet">

</head>
<body>
<!-- header1-->
		<div class="header1">
            <div class="main">
                <div class="left" style="left:200px; top:20px">
                    <font size="6">我国临床试验情况分析系统</font>
                </div>
<!-- 搜索栏 -->
<div class="container">{% csrf_token %}
    <form  class="parent" method="post">

        <input type="text" name="clinialtrial" placeholder="请输入...">
        <input type="submit" value="&emsp;搜&emsp;索&emsp;">
    </form>
</div>
        <!-- 注册/登录 -->
                <div class="right" style="right: 200px; top: 20px">
                    <font size="4"><a href="/clinicaltrial/data">可视化大屏</a></font>
                </div>
		    </div>
        </div>
<div class="ditu main">
    <div class="left">
        <ul class="list">
            <li>
            <div class="tongji">
<div class="page-content">
    <div class="row">
        <div class="col-md-2">
            <div class="sidebar content-box" style="display: block;">
                <ul class="nav">
                    <!-- Main menu -->
                    <li class="submenu">
                        <a href="#">
                            <i class="glyphicon glyphicon-list"></i> 我国临床试验注册数量
                            <span class="caret pull-right"></span>
                        </a>
                        <!-- Sub menu -->
                        <ul>
                            <li class="current"><i class="glyphicon glyphicon-minus"></i> 2018&emsp;&emsp;&emsp;{{ a }}</li>
                            <li><i class="glyphicon glyphicon-record"></i> 2019&emsp;&emsp;&emsp;{{ b }}</li>
                            <li><i class="glyphicon glyphicon-pencil"></i> 2020&emsp;&emsp;&emsp;{{ c }}</li>
                            <li><i class="glyphicon glyphicon-pencil"></i> 2021&emsp;&emsp;&emsp;{{ d }}</li>
                            <li><a href="/clinicaltrial/bar_toolbox"><i class="glyphicon glyphicon-record"></i>可视化展示</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#">
                            <i class="glyphicon glyphicon-list"></i> For Anzsrc Data
                            <span class="caret pull-right"></span>
                        </a>
                        <!-- Sub menu -->
                        <ul>
                            {% for fad in fads %}
                            <li ><i class="glyphicon glyphicon-list"></i>{{ fad.no }}&emsp;&emsp;{{ fad.quantity }}</li>
                            {% endfor %}
                            <li><a href="/clinicaltrial/pie_show"><i class="glyphicon glyphicon-record"></i>可视化展示</a></li>
                        </ul>
                    </li>
                                    <li class="submenu">
                        <a href="#">
                            <i class="glyphicon glyphicon-list"></i> 临床试验阶段
                            <span class="caret pull-right"></span>
                        </a>
                        <!-- Sub menu -->
                        <ul>
                            <li ><i class="glyphicon glyphicon-list"></i>Phase 0&emsp;&emsp;{{ phase0 }}</li>
                            <li ><i class="glyphicon glyphicon-list"></i>Phase 1&emsp;&emsp;{{ phase1 }}</li>
                            <li ><i class="glyphicon glyphicon-list"></i>Phase 2&emsp;&emsp;{{ phase2 }}</li>
                            <li ><i class="glyphicon glyphicon-list"></i>Phase 3&emsp;&emsp;{{ phase3 }}</li>
                            <li ><i class="glyphicon glyphicon-list"></i>Phase 4&emsp;&emsp;{{ phase4 }}</li>
                            <li ><i class="glyphicon glyphicon-list"></i>N/A&emsp;&emsp;{{ na }}</li>
                            <li><a href="/clinicaltrial/phase"><i class="glyphicon glyphicon-record"></i>可视化展示</a></li>
                        </ul>
                    </li>
                    <li class="submenu">
                        <a href="#">
                            <i class="glyphicon glyphicon-list"></i> 地区
                            <span class="caret pull-right"></span>
                        </a>
                        <!-- Sub menu -->
                        <ul>
                            {% for state in states %}
                            <li ><i class="glyphicon glyphicon-list"></i>{{ state.state }}&emsp;&emsp;{{ state.state_count }}</li>
                            {% endfor %}
                            <li><a href="/clinicaltrial/city"><i class="glyphicon glyphicon-pencil"></i>可视化显示</a></li>
                        </ul>
                    </li>

                    <li class="submenu">
                        <a href="#">
                            <i class="glyphicon glyphicon-list"></i> 设置
                            <span class="caret pull-right"></span>
                        </a>
                        <!-- Sub menu -->
                        <ul>
                            <li><a href="/clinicaltrial/login">登入</a></li>
                            <li><a href="/clinicaltrial/register">注册</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div></div>
        <div class="text">
        <ul class="clearfix">
                    {% for clinialtrial in clinialtrials %}
                    <a href="#" class="title">{{clinialtrial.title}}</a>
                        <p><font size="4">注册年份:{{ clinialtrial.start_year }}&emsp;&emsp;城市:{{ clinialtrial.city1 }},{{ clinialtrial.state1 }},{{ clinialtrial.country1 }}</font></p>
                        <p><font size="4">成员:{{ clinialtrial.investigators_contacts }}&emsp;&emsp;阶段：{{ clinialtrial.phase }}</font></p>
                        <font size="4"><a href="{{ clinialtrial.dimensions_url }}">点击查看详情页</a></font>
                        <p class="desc"><font size="4">{{clinialtrial.abstract}}</font></p>
                    <br>
                    {% endfor %}
        </ul>
                </div>
            </li>
        </ul>
    </div>
</div>



<link href="/static/vendors/datatables/dataTables.bootstrap.css" rel="stylesheet" media="screen">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery.js"></script>
<!-- jQuery UI -->
<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/vendors/datatables/js/jquery.dataTables.min.js"></script>
<script src="/static/vendors/datatables/dataTables.bootstrap.js"></script>
<script src="/static/js/custom.js"></script>
</body>
</html>

pyecharts/final design/test01/templates/login_n.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="renderer" content="webkit" />
		<title>登陆</title>
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"/>
        <script src="https://cdn.bootcss.com/jquery/3.0.0/jquery.min.js"></script>
        <script src="https://cdn.staticfile.org/echarts/4.3.0/echarts.min.js"></script>
        <script type="text/javascript" src="https://assets.pyecharts.org/assets/echarts.min.js"></script>

	</head>
	<body>
		
<!-- header1-->
		<div class="header1">
            <div class="main">
                <div class="left" style="left:200px; top:20px">
                    <font size="6">我国临床试验分析系统-登入</font>
                </div></div></div>

		
{#		<!--轮播图-->#}
{#		<div class="main">#}
{#			<div class="slide-wrap">#}
{#			#}
{#				<div class="slide-content">#}
{#					<a href="#"><div class="slide-item" style="background: url(images/banner1.png) no-repeat center center;"></div></a>#}
{#					<a href="#"><div class="slide-item" style="display: none; background: url(images/banner2.jpg) no-repeat center center;"></div></a>#}
{#					<a href="#"><div class="slide-item" style="display: none; background: url(images/banner3.jpg) no-repeat center center;"></div></a>#}
{#				</div>#}
{#				#}
{#				<div id="pagination">#}
{#				</div>#}
{#				#}
{#			</div>#}
{#		</div>#}
		
		<!--登录-->
<div class="register main">
       <form action="/clinicaltrial/login/" method="post">
        {% csrf_token %}

			<div class="form-item">
				<span>用户名：</span><input type="text" id="username" name="username"/>
			</div>

            <div class="form-item">
				<span>密码：</span><input type="password" id="password" name="password" />
			</div>

            <div class="form-item">
                <button id="register-button">登&emsp;入</button>
{#				<input type="submit" id="register-button" value="登&emsp;录">#}
			</div>



    </form>
</div>

	</body>
</html>

pyecharts/final design/test01/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>查询</title>
</head>
<body>
    <from ation="/clinicaltrial/show/" method="post">
        {% csrf_token %}
            <label>请输入搜索内容:</label><input type="text" name="title">
            <label></label>
    </from>

    <div id="content">
            <ul class="clearfix">
                {% for data in datas %}
            <li>
                <h1 class="h1">{{ data.title }}</h1>
            </li>
                {% endfor %}
        </ul>
    </div>
</body>
</html>

pyecharts/final design/test01/templates/show_add.html
<!DOCTYPE html>
<html lang="en-us"><head>
<title>Add clinicaltrial</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">

  <link rel="stylesheet" type="text/css" href="/static/admin/css/nav_sidebar.css">
  <script src="/static/admin/js/nav_sidebar.js" defer=""></script>

<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">


<script src="/admin/jsi18n/"></script>
<script src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script src="/static/admin/js/jquery.init.js"></script>
<script src="/static/admin/js/core.js"></script>
<script src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script src="/static/admin/js/actions.js"></script>
<script src="/static/admin/js/urlify.js"></script>
<script src="/static/admin/js/prepopulate.js"></script>
<script src="/static/admin/js/vendor/xregexp/xregexp.js"></script>


    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=" app-clinicaltrial model-clinicaltrial change-form" data-admin-utc-offset="0">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name"><a href="/admin/">添加新的试验</a></h1>

        </div>


        <div id="user-tools">

                Welcome/

                <a href="/admin/logout/">Log out</a>

        </div>



    </div>
    <!-- END Header -->



    <div class="main shifted" id="main">



<button class="sticky toggle-nav-sidebar" id="toggle-nav-sidebar" aria-label="Toggle navigation"></button>
<nav class="sticky" id="nav-sidebar">





    <div class="app-clinicaltrial module current-app">
      <table>
        <caption>
          <a href="/admin/clinicaltrial/" class="section" title="Models in the Clinicaltrial application">Clinicaltrial</a>
        </caption>

          <tbody><tr class="model-clinicaltrial current-model">

              <th scope="row"><a href="/admin/clinicaltrial/clinicaltrial/" aria-current="page">Clinicaltrials</a></th>



              <td><a href="/admin/clinicaltrial/clinicaltrial/add/" class="addlink">Add</a></td>



          </tr>

      </tbody></table>
    </div>



</nav>



      <div class="content">



        <!-- Content -->
        <div id="content" class="colM">

          <h1>Add clinicaltrial</h1>
          <div id="content-main">



<form method="post" id="clinicaltrial_form" novalidate=""><input type="hidden" name="csrfmiddlewaretoken" value="bXZoLOPYAcZAMKLtjWCFZoz0HzF2iioL4QMnYhL2VjtXX8ciQa807jMyVVrmbizM">
<div>







  <fieldset class="module aligned ">



        <div class="form-row field-trial_id">


                <div>


                        <label class="required" for="id_trial_id">Trial id:</label>

                            <input type="text" name="trial_id" class="vTextField" maxlength="45" required="" id="id_trial_id">



                </div>

        </div>

        <div class="form-row field-title">


                <div>


                        <label for="id_title">Title:</label>

                            <input type="text" name="title" class="vTextField" maxlength="500" id="id_title">



                </div>

        </div>

        <div class="form-row field-brief_title">


                <div>


                        <label for="id_brief_title">Brief title:</label>

                            <input type="text" name="brief_title" class="vTextField" maxlength="500" id="id_brief_title">



                </div>

        </div>

        <div class="form-row field-acronym">


                <div>


                        <label for="id_acronym">Acronym:</label>

                            <input type="text" name="acronym" class="vTextField" maxlength="500" id="id_acronym">



                </div>

        </div>

        <div class="form-row field-abstract">


                <div>


                        <label for="id_abstract">Abstract:</label>

                            <input type="text" name="abstract" class="vTextField" maxlength="1000" id="id_abstract">



                </div>

        </div>

        <div class="form-row field-detailed_description">


                <div>


                        <label for="id_detailed_description">Detailed description:</label>

                            <input type="text" name="detailed_description" class="vTextField" maxlength="1500" id="id_detailed_description">



                </div>

        </div>

        <div class="form-row field-start_year">


                <div>


                        <label for="id_start_year">Start year:</label>

                            <input type="number" name="start_year" class="vIntegerField" id="id_start_year">



                </div>

        </div>


        <div class="form-row field-phase">


                <div>


                        <label for="id_phase">Phase:</label>

                            <input type="text" name="phase" class="vTextField" maxlength="45" id="id_phase">



                </div>

        </div>


        <div class="form-row field-gender">


                <div>


                        <label for="id_gender">Gender:</label>

                            <input type="text" name="gender" class="vTextField" maxlength="30" id="id_gender">



                </div>

        </div>

        <div class="form-row field-registry">


                <div>


                        <label for="id_registry">Registry:</label>

                            <input type="text" name="registry" class="vTextField" maxlength="30" id="id_registry">



                </div>

        </div>

        <div class="form-row field-investigators_contacts">


                <div>


                        <label for="id_investigators_contacts">Investigators contacts:</label>

                            <input type="text" name="investigators_contacts" class="vTextField" maxlength="500" id="id_investigators_contacts">



                </div>

        </div>

        <div class="form-row field-dimensions_url">


                <div>


                        <label for="id_dimensions_url">Dimensions url:</label>

                            <input type="text" name="dimensions_url" class="vTextField" maxlength="100" id="id_dimensions_url">



                </div>

        </div>

        <div class="form-row field-for_anzsrc_categories">


                <div>


                        <label for="id_for_anzsrc_categories">For anzsrc categories:</label>

                            <input type="text" name="for_anzsrc_categories" class="vTextField" maxlength="500" id="id_for_anzsrc_categories">



                </div>

        </div>

        <div class="form-row field-rcdc_categories">


                <div>


                        <label for="id_rcdc_categories">Rcdc categories:</label>

                            <input type="text" name="rcdc_categories" class="vTextField" maxlength="500" id="id_rcdc_categories">



                </div>

        </div>

        <div class="form-row field-hrcs_hc_categories">


                <div>


                        <label for="id_hrcs_hc_categories">Hrcs hc categories:</label>

                            <input type="text" name="hrcs_hc_categories" class="vTextField" maxlength="500" id="id_hrcs_hc_categories">



                </div>

        </div>


        <div class="form-row field-city1">


                <div>


                        <label for="id_city1">City1:</label>

                            <input type="text" name="city1" class="vTextField" maxlength="45" id="id_city1">



                </div>

        </div>


        <div class="form-row field-state1">


                <div>


                        <label for="id_state1">State1:</label>

                            <input type="text" name="state1" class="vTextField" maxlength="45" id="id_state1">



                </div>

        </div>


        <div class="form-row field-country1">


                <div>


                        <label for="id_country1">Country1:</label>

                            <input type="text" name="country1" class="vTextField" maxlength="45" id="id_country1">



                </div>

        </div>



</fieldset>













<div class="submit-row">

<input type="submit" value="Save" class="default" name="_save">

</div>



    <script id="django-admin-form-add-constants" src="/static/admin/js/change_form.js" data-model-name="clinicaltrial" async="">
    </script>




<script id="django-admin-prepopulated-fields-constants" src="/static/admin/js/prepopulate_init.js" data-prepopulated-fields="[]">
</script>


</div>
</form></div>


          <br class="clear">
        </div>
        <!-- END Content -->
        <div id="footer"></div>
      </div>
    </div>
</div>
<!-- END Container -->


</body></html>